version: '3.2'
services:
  postgres:
    container_name: lab-2-db
    image: postgres:15
    ports:
      - '5432:5432'
    env_file:
      - db.env
    volumes:
        - ./db-data:/var/lib/postgresql/data
